// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Onyx_CustomDataManual","status":true,"description":"(Onyx) Carga manual de JSON custom desde /data/custom/ en $dataCustom.","parameters":{}},
{"name":"Onyx_MaxValues","status":true,"description":"(Onyx) Permite configurar los máximos de nivel, ítems y parámetros (RPG Maker MV)","parameters":{"maxActorLevel":"99","maxItemsPerStack":"999","maxMHP":"9999","maxMMP":"9999","maxOtherParam":"999"}},
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"CustomLogo","status":true,"description":"Shows RPG Maker and user logos at the start of the game.","parameters":{"logo1":"","logo1ImageName":"MadeWithMv","logo1Skippable":"true","logo1Coordinate":"","logo1X":"408","logo1Y":"312","logo1Origin":"0.5","logo1Time":"","logo1FadeinFrames":"12","logo1FadeoutFrames":"12","logo1DurationFrames":"120","logo2":"","logo2ImageName":"","logo2Skippable":"true","logo2Coordinate":"","logo2X":"408","logo2Y":"312","logo2Origin":"0.5","logo2Time":"","logo2FadeinFrames":"12","logo2FadeoutFrames":"12","logo2DurationFrames":"120","logo3":"","logo3ImageName":"","logo3Skippable":"true","logo3Coordinate":"","logo3X":"408","logo3Y":"312","logo3Origin":"0.5","logo3Time":"","logo3FadeinFrames":"12","logo3FadeoutFrames":"12","logo3DurationFrames":"120","allowTotalSkip":"true"}},
{"name":"SkillTala","status":true,"description":"(Onyx) Skill: Tala - variables, constantes y EXP por tabla (RPG Maker MV)","parameters":{"varSkillLevel":"1","varExpActual":"2","varExpSiguiente":"3","varMaterialId":"38"}}
];
